<a href="https://colab.research.google.com/github/abhishek04bit/Assessment/blob/main/case_study2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
filepath = "/content/drive/MyDrive/dataset/House_Pricing.csv"
df_house = pd.read_csv(filepath)
df_house.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

In [ ]:
df_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [ ]:
df_house.describe()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
count,2.161300e+04,2.160900e+04,21613.000000,21609.000000,21604.000000,2.160400e+04,21613.000000,21613.000000,21610.000000,21613.000000,21613.000000,21613.000000,21612.000000,21612.000000,21612.000000,21612.000000,21613.000000
mean,4.580302e+09,5.401984e+05,3.370842,2.114732,2079.931772,1.510776e+04,1.494309,7.623467,1788.344193,291.509045,46.994864,84.402258,98077.937766,47.560048,-122.213892,1986.538914,12768.455652
std,2.876566e+09,3.673890e+05,0.930062,0.770138,918.487597,4.142827e+04,0.539989,1.105439,827.982604,442.575043,29.373411,401.679240,53.505425,0.138565,0.140830,685.404255,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,1.000000,290.000000,0.000000,3.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1429.250000,5.040000e+03,1.000000,7.000000,1190.000000,0.000000,21.000000,0.000000,98033.000000,47.470975,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.617500e+03,1.500000,7.000000,1560.000000,0.000000,43.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068825e+04,2.000000,8.000000,2210.000000,560.000000,67.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,10.000000,9410.000000,4820.000000,118.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [ ]:
df_house.isna().sum()

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [ ]:
for i in df_house.columns:
  print(df_house[i].value_counts())

ID
795000620     3
7520000695    2
7200179       2
3904100089    2
6308000010    2
             ..
5602000275    1
1786200010    1
1525079069    1
126049167     1
1211000185    1
Name: count, Length: 21436, dtype: int64
Date House was Sold
15 April 2016        2231
14 July 2017         2211
14 June 2017         2180
14 August 2017       1940
14 October 2017      1878
15 March 2016        1875
14 September 2017    1774
14 May 2017          1768
14 December 2017     1471
14 November 2017     1411
15 February 2016     1250
15 January 2016       978
15 May 2016           646
Name: count, dtype: int64
Sale Price
350000.0    172
450000.0    171
550000.0    159
500000.0    152
425000.0    150
           ...
357186.0      1
747450.0      1
589999.0      1
402723.0      1
999999.0      1
Name: count, Length: 3625, dtype: int64
No of Bedrooms
3     9824
4     6882
2     2760
5     1601
6      272
1      199
7       38
0       13
8       13
9        6
10       3
11       1
33       1
Name: count, dtype: int64
No of Bathrooms
2.50    5380
1.00    3851
1.75    3048
2.25    2045
2.00    1930
1.50    1446
2.75    1185
3.00     753
3.50     730
3.25     589
3.75     155
4.00     136
4.50     100
4.25      79
0.75      72
4.75      23
5.00      21
5.25      13
0.00      10
5.50      10
1.25       9
6.00       6
0.50       4
5.75       4
6.75       2
8.00       2
6.50       2
6.25       2
7.75       1
7.50       1
Name: count, dtype: int64
Flat Area (in Sqft)
1300.0    138
1400.0    135
1440.0    133
1660.0    129
1800.0    129
         ...
2507.0      1
9890.0      1
5584.0      1
1961.0      1
5660.0      1
Name: count, Length: 1036, dtype: int64
Lot Area (in Sqft)
5000.0     357
6000.0     290
4000.0     251
7200.0     220
4800.0     120
          ...
2642.0       1
2656.0       1
15035.0      1
638.0        1
13405.0      1
Name: count, Length: 9778, dtype: int64
No of Floors
1.0    10680
2.0     8241
1.5     1910
3.0      613
2.5      161
3.5        8
Name: count, dtype: int64
Waterfront View
No     21450
Yes      163
Name: count, dtype: int64
No of Times Visited
Twice     963
Thrice    510
Once      332
Four      319
Name: count, dtype: int64
Condition of the House
Fair         14031
Good          5679
Excellent     1701
Okay           172
Bad             30
Name: count, dtype: int64
Overall Grade
7     8981
8     6068
9     2615
6     2038
10    1623
5      242
4       29
2       13
3        3
1        1
Name: count, dtype: int64
Area of the House from Basement (in Sqft)
1300.0    212
1010.0    210
1200.0    206
1220.0    192
1140.0    184
         ...
2244.0      1
1606.0      1
894.0       1
1715.0      1
1425.0      1
Name: count, Length: 946, dtype: int64
Basement Area (in Sqft)
0       13126
600       221
700       218
500       214
800       206
        ...
176         1
225         1
1275        1
274         1
248         1
Name: count, Length: 306, dtype: int64
Age of House (in Years)
4      559
12     454
13     450
14     433
15     422
      ...
85      30
117     29
116     27
83      24
84      21
Name: count, Length: 116, dtype: int64
Renovated Year
0       20699
2014       91
2013       37
2003       36
2005       35
        ...
1948        1
1951        1
1959        1
1934        1
1944        1
Name: count, Length: 70, dtype: int64
Zipcode
98103.0    602
98038.0    590
98115.0    583
98052.0    574
98117.0    553
          ...
98102.0    105
98010.0    100
98024.0     81
98148.0     57
98039.0     50
Name: count, Length: 70, dtype: int64
Latitude
47.5491    17
47.6624    17
47.6846    17
47.5322    17
47.6711    16
           ..
47.6026     1
47.7747     1
47.3421     1
47.4221     1
47.6180     1
Name: count, Length: 5034, dtype: int64
Longitude
-122.290    116
-122.300    111
-122.362    104
-122.291    100
-122.372     99
           ...
-121.316      1
-121.941      1
-121.480      1
-121.767      1
-122.420      1
Name: count, Length: 752, dtype: int64
Living Area after Renovation (in Sqft)
1540.0    197
1440.0    195
1560.0    192
1500.0    181
1460.0    169
         ...
2513.0      1
2725.0      1
1955.0      1
2527.0      1
4443.0      1
Name: count, Length: 777, dtype: int64
Lot Area after Renovation (in Sqft)
5000    427
4000    357
6000    289
7200    211
4800    145
       ...
5259      1
3836      1
5009      1
1395      1
5761      1
Name: count, Length: 8689, dtype: int64

In [ ]:
df_house.shape

(21613, 21)

#**Handling Missing Values**

In [ ]:
Q1 = df_house["Sale Price"].quantile(0.25)
Q3 = df_house["Sale Price"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers = df_house[(df_house["Sale Price"]<lower_bound) | (df_house["Sale Price"]>upper_bound)]
len(outliers)

1159

In [ ]:
median_sale_price = df_house["Sale Price"].median()
df_house["Sale Price"] = df_house["Sale Price"].fillna(median_sale_price)

In [ ]:
Q1 = df_house["No of Bathrooms"].quantile(0.25)
Q3 = df_house["No of Bathrooms"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers = df_house[(df_house["No of Bathrooms"]<lower_bound) | (df_house["No of Bathrooms"]>upper_bound)]
len(outliers)

571

In [ ]:
median_bathroom = df_house["No of Bathrooms"].median()
df_house["No of Bathrooms"] = df_house["No of Bathrooms"].fillna(median_bathroom)

In [ ]:
Q1 = df_house["Flat Area (in Sqft)"].quantile(0.25)
Q3 = df_house["Flat Area (in Sqft)"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers = df_house[(df_house["Flat Area (in Sqft)"]<lower_bound) | (df_house["Flat Area (in Sqft)"]>upper_bound)]
len(outliers)

572

In [ ]:
median_flat_area = df_house["Flat Area (in Sqft)"].median()
df_house["Flat Area (in Sqft)"] = df_house["Flat Area (in Sqft)"].fillna(median_flat_area)

In [ ]:
Q1 = df_house["Lot Area (in Sqft)"].quantile(0.25)
Q3 = df_house["Lot Area (in Sqft)"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers = df_house[(df_house["Lot Area (in Sqft)"]<lower_bound) | (df_house["Lot Area (in Sqft)"]>upper_bound)]
len(outliers)

2423

In [ ]:
median_lot_area = df_house["Lot Area (in Sqft)"].median()
df_house["Lot Area (in Sqft)"] = df_house["Lot Area (in Sqft)"].fillna(median_lot_area)

In [ ]:
df_house["No of Times Visited"].mode()

0    Twice
Name: No of Times Visited, dtype: object

In [ ]:
df_house["No of Times Visited"] = df_house["No of Times Visited"].fillna("Twice")

In [ ]:
Q1 = df_house["Area of the House from Basement (in Sqft)"].quantile(0.25)
Q3 = df_house["Area of the House from Basement (in Sqft)"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers = df_house[(df_house["Area of the House from Basement (in Sqft)"]<lower_bound) | (df_house["Area of the House from Basement (in Sqft)"]>upper_bound)]
len(outliers)

610

In [ ]:
median_area_from_basement = df_house["Area of the House from Basement (in Sqft)"].median()
df_house["Area of the House from Basement (in Sqft)"] = df_house["Area of the House from Basement (in Sqft)"].fillna(median_area_from_basement)

In [ ]:
Q1 = df_house["Zipcode"].quantile(0.25)
Q3 = df_house["Zipcode"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers = df_house[(df_house["Zipcode"]<lower_bound) | (df_house["Zipcode"]>upper_bound)]
len(outliers)

0

In [ ]:
mean_zipcode = df_house["Zipcode"].mean()
df_house["Zipcode"] = df_house["Zipcode"].fillna(mean_zipcode)

In [ ]:
Q1 = df_house["Latitude"].quantile(0.25)
Q3 = df_house["Latitude"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers = df_house[(df_house["Latitude"]<lower_bound) | (df_house["Latitude"]>upper_bound)]
len(outliers)

2

In [ ]:
mean_latitude = df_house["Latitude"].mean()
df_house["Latitude"] = df_house["Latitude"].fillna(mean_latitude)

In [ ]:
Q1 = df_house["Longitude"].quantile(0.25)
Q3 = df_house["Longitude"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers = df_house[(df_house["Longitude"]<lower_bound) | (df_house["Longitude"]>upper_bound)]
len(outliers)

256

In [ ]:
median_longitude = df_house["Longitude"].median()
df_house["Longitude"] = df_house["Longitude"].fillna(median_longitude)

In [ ]:
Q1 = df_house["Living Area after Renovation (in Sqft)"].quantile(0.25)
Q3 = df_house["Living Area after Renovation (in Sqft)"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers = df_house[(df_house["Living Area after Renovation (in Sqft)"]<lower_bound) | (df_house["Living Area after Renovation (in Sqft)"]>upper_bound)]
len(outliers)

544

In [ ]:
median_living_area_ren = df_house["Living Area after Renovation (in Sqft)"].median()
df_house["Living Area after Renovation (in Sqft)"] = df_house["Living Area after Renovation (in Sqft)"].fillna(median_living_area_ren)

In [ ]:
#after filling missing values
df_house.isna().sum()

ID                                           0
Date House was Sold                          0
Sale Price                                   0
No of Bedrooms                               0
No of Bathrooms                              0
Flat Area (in Sqft)                          0
Lot Area (in Sqft)                           0
No of Floors                                 0
Waterfront View                              0
No of Times Visited                          0
Condition of the House                       0
Overall Grade                                0
Area of the House from Basement (in Sqft)    0
Basement Area (in Sqft)                      0
Age of House (in Years)                      0
Renovated Year                               0
Zipcode                                      0
Latitude                                     0
Longitude                                    0
Living Area after Renovation (in Sqft)       0
Lot Area after Renovation (in Sqft)          0
dtype: int64

#**Scaling**

In [ ]:
num_cols = df_house.select_dtypes(include=["int64","float64"]).columns
print(num_cols)

Index(['ID', 'Sale Price', 'No of Bedrooms', 'No of Bathrooms',
       'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors',
       'Overall Grade', 'Area of the House from Basement (in Sqft)',
       'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year',
       'Zipcode', 'Latitude', 'Longitude',
       'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)'],
      dtype='object')

In [ ]:
#before scaling
df_house.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,Twice,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,Twice,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,Twice,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,Twice,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,Twice,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

In [ ]:
cols = ['ID', 'Sale Price', 'No of Bedrooms', 'No of Bathrooms',
       'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors',
       'Overall Grade', 'Area of the House from Basement (in Sqft)',
       'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year',
       'Zipcode', 'Latitude', 'Longitude',
       'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)',
       'Area of the House from Basement (in Sqft)']

In [ ]:
std_scaler = StandardScaler()
df_house[cols] = std_scaler.fit_transform(df_house[cols])

In [ ]:
#after scaling
df_house.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,0.886146,14 October 2017,-0.866430,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,No,Twice,...,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870219,-0.352541,-0.306112,-0.943328,-0.260715
1,0.637511,14 December 2017,-0.005939,-0.398737,0.175628,0.533757,-0.189832,0.936506,No,Twice,...,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879619,1.161620,-0.746380,-0.432658,-0.187868
2,0.365444,15 February 2016,-0.980490,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,No,Twice,...,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933365,1.283590,-0.135686,1.070173,-0.172375
3,-0.727656,14 December 2017,0.173727,0.676485,1.149589,-0.130528,-0.243962,-0.915427,No,Twice,...,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085216,-0.283256,-1.271861,-0.914147,-0.284522
4,-0.912881,15 February 2016,-0.082161,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,No,Twice,...,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073599,0.409591,1.199321,-0.272161,-0.192849

#**encoding**

In [ ]:
cat_cols = df_house.select_dtypes(include=["object"]).columns
print(cat_cols)

Index(['Date House was Sold', 'Waterfront View', 'No of Times Visited',
       'Condition of the House'],
      dtype='object')

In [ ]:
#before label encoding
df_house.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,0.886146,14 October 2017,-0.866430,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,No,Twice,...,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870219,-0.352541,-0.306112,-0.943328,-0.260715
1,0.637511,14 December 2017,-0.005939,-0.398737,0.175628,0.533757,-0.189832,0.936506,No,Twice,...,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879619,1.161620,-0.746380,-0.432658,-0.187868
2,0.365444,15 February 2016,-0.980490,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,No,Twice,...,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933365,1.283590,-0.135686,1.070173,-0.172375
3,-0.727656,14 December 2017,0.173727,0.676485,1.149589,-0.130528,-0.243962,-0.915427,No,Twice,...,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085216,-0.283256,-1.271861,-0.914147,-0.284522
4,-0.912881,15 February 2016,-0.082161,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,No,Twice,...,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073599,0.409591,1.199321,-0.272161,-0.192849

In [ ]:
label_encoder_obj = LabelEncoder()
df_house["Condition of the House"] = label_encoder_obj.fit_transform(df_house["Condition of the House"])
df_house["No of Times Visited"] = label_encoder_obj.fit_transform(df_house["No of Times Visited"])

In [ ]:
#after label encoding
df_house.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,0.886146,14 October 2017,-0.866430,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,No,3,...,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870219,-0.352541,-0.306112,-0.943328,-0.260715
1,0.637511,14 December 2017,-0.005939,-0.398737,0.175628,0.533757,-0.189832,0.936506,No,3,...,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879619,1.161620,-0.746380,-0.432658,-0.187868
2,0.365444,15 February 2016,-0.980490,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,No,3,...,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933365,1.283590,-0.135686,1.070173,-0.172375
3,-0.727656,14 December 2017,0.173727,0.676485,1.149589,-0.130528,-0.243962,-0.915427,No,3,...,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085216,-0.283256,-1.271861,-0.914147,-0.284522
4,-0.912881,15 February 2016,-0.082161,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,No,3,...,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073599,0.409591,1.199321,-0.272161,-0.192849

In [ ]:
#before onehot encoding
df_house.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,0.886146,14 October 2017,-0.866430,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,No,3,...,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870219,-0.352541,-0.306112,-0.943328,-0.260715
1,0.637511,14 December 2017,-0.005939,-0.398737,0.175628,0.533757,-0.189832,0.936506,No,3,...,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879619,1.161620,-0.746380,-0.432658,-0.187868
2,0.365444,15 February 2016,-0.980490,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,No,3,...,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933365,1.283590,-0.135686,1.070173,-0.172375
3,-0.727656,14 December 2017,0.173727,0.676485,1.149589,-0.130528,-0.243962,-0.915427,No,3,...,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085216,-0.283256,-1.271861,-0.914147,-0.284522
4,-0.912881,15 February 2016,-0.082161,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,No,3,...,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073599,0.409591,1.199321,-0.272161,-0.192849

In [ ]:
#after onehot encoding
ohe_cols = ['Date House was Sold','Waterfront View']
df_ohe = pd.get_dummies(df_house, columns = ohe_cols, dtype = int)
df_ohe.head()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,No of Times Visited,Condition of the House,Overall Grade,...,Date House was Sold_14 November 2017,Date House was Sold_14 October 2017,Date House was Sold_14 September 2017,Date House was Sold_15 April 2016,Date House was Sold_15 February 2016,Date House was Sold_15 January 2016,Date House was Sold_15 March 2016,Date House was Sold_15 May 2016,Waterfront View_No,Waterfront View_Yes
0,0.886146,-0.866430,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,3,2,-0.564013,...,0,1,0,0,0,0,0,0,1,0
1,0.637511,-0.005939,-0.398737,0.175628,0.533757,-0.189832,0.936506,3,2,-0.564013,...,0,0,0,0,0,0,0,0,1,0
2,0.365444,-0.980490,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,3,2,-1.468651,...,0,0,0,0,1,0,0,0,1,0
3,-0.727656,0.173727,0.676485,1.149589,-0.130528,-0.243962,-0.915427,3,1,-0.564013,...,0,0,0,0,0,0,0,0,1,0
4,-0.912881,-0.082161,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,3,2,0.340626,...,0,0,0,0,1,0,0,0,1,0